.TH DDUPDATE_NETRC_TO_KEYRING "8" "Last change: Apr 2022" "ddupdate-config" "System Administration Utilities"
.SH NAME
.P
\fBddupdate_netrc_to_keyring\fR - ddupdate configuration migration tool.

.SH SYNOPSIS
\fBddupdate_netrc_to_keyring\fR

.SH DESCRIPTION
Simple script which reads all entries in \fI~/.netrc\fR and copies
them to the system keyring in a format which can be used by the
ddupdate keyring authentication plugin. 

.SH SEE ALSO
.TP 4
.B ddupdate(8)

