#!/usr/bin/python3

''' ddupdate main script, invokes ddupdate.main.main(). '''

# pylint: disable=invalid-name, wrong-import-position

import os.path
import sys

home = os.path.abspath(os.path.dirname(__file__))

sys.path.insert(0, os.path.join(home, 'lib'))
os.chdir(home)

try:
    import lib.ddupdate.main as main
except ModuleNotFoundError:
    import ddupdate.main as main

main.main()
