#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.7.2
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.7.2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask ddupdate.service ddupdate.timer >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge ddupdate.service ddupdate.timer >/dev/null
		deb-systemd-helper unmask ddupdate.service ddupdate.timer >/dev/null
	fi
fi
# End automatically added section
