#!/bin/sh
set -e

sed -i 's|debian/tmp/|/|' /usr/lib/python3/dist-packages/ddupdate/install.conf || :
sed -i 's|debian/tmp$|/|' /usr/lib/python3/dist-packages/ddupdate/install.conf || :

#DEBHELPER#
exit 0

